// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS6tsV8skIUaz-Ud44ZZ5jSCDdyGOVbpk',
    appId: '1:341665435745:web:9b5852a05e42e078cc9a20',
    messagingSenderId: '341665435745',
    projectId: 'soup-rewrd-app',
    authDomain: 'soup-rewrd-app.firebaseapp.com',
    storageBucket: 'soup-rewrd-app.firebasestorage.app',
    measurementId: 'G-3M23X4J1KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Z7AyPUaE6A42XuTuuk5N3gFc0nknw18',
    appId: '1:341665435745:android:6b4bdbb8e18103aecc9a20',
    messagingSenderId: '341665435745',
    projectId: 'soup-rewrd-app',
    storageBucket: 'soup-rewrd-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbtRT4x02hMKYhLBetxOxk_Y523sotMm8',
    appId: '1:341665435745:ios:5aac21562ccea38ecc9a20',
    messagingSenderId: '341665435745',
    projectId: 'soup-rewrd-app',
    storageBucket: 'soup-rewrd-app.firebasestorage.app',
    iosBundleId: 'com.kanamurayusaku.soupRewards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbtRT4x02hMKYhLBetxOxk_Y523sotMm8',
    appId: '1:341665435745:ios:5aac21562ccea38ecc9a20',
    messagingSenderId: '341665435745',
    projectId: 'soup-rewrd-app',
    storageBucket: 'soup-rewrd-app.firebasestorage.app',
    iosBundleId: 'com.kanamurayusaku.soupRewards',
  );
}
